# Generated by Django 4.2.29 on 2026-04-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('option_a', models.CharField(max_length=255, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Вариант C')),
                ('option_d', models.CharField(max_length=255, verbose_name='Вариант D')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='Правильный ответ (A/B/C/D)')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение')),
                ('category', models.CharField(choices=[('author', 'Автор'), ('work', 'Произведение'), ('image', 'По картинке')], default='author', max_length=20)),
            ],
        ),
    ]
